var css = {
	"general": "body{font-family:sans-serif;text-align:center;margin:0;font-size:16px}hr{margin:2.5em auto}hr.mediumwidth{margin:2.5em auto}.mediumwidth{font-size:16px;width:40%;margin-left:30%;margin-top:.3em;margin-bottom:.3em}@media(max-width:870px){.mediumwidth{width:70%;margin-left:15%}.row [class*='c']{width:100%;display:block;margin:1% auto}.row:last-child column{margin-bottom:2.5em}}@media(max-width:520px){.mediumwidth{width:100%;margin-left:0}hr.mediumwidth{width:auto}}",
	"buttons": "i,button{font-family:Lucida Sans Unicode,Lucida Grande,sans-serif}button{background:#aaa;box-shadow:3px 3px 0 black;color:#f3f3f3 !important;font-size:2.5em;padding:15px 40px 16px;text-decoration:none;margin:.3em .7em .3em .7em;cursor:pointer;border:0}button.smooth{transition:background .15s ease-in-out}button.btn-a{background:#0ae}button.btn-a:hover{background:#0098d5}button.btn-a:active{background:#0086bb}button.btn-b{background:#3c5}button.btn-b:hover{background:#2eb84d}button.btn-b:active{background:#29a344}button.btn-c{background:#d33}button.btn-c:hover{background:#d32323}button.btn-c:active{background:#bd2020}button.btn-small{padding:7px 19px 10px;font-size:16px}",
	"grid": ".row{line-height:2em;margin-top:2%;height:2em}column{float:left;margin:auto 1%}.ie column{margin:auto .7%}.c10{width:98%}.c9{width:88%}.c8{width:78%}.c7{width:68%}.c6{width:58%}.c5{width:48%}.c4{width:38%}.c3{width:28%}.c2{width:18%}.c1{width:8%}",
	"headings": "h1{font-size:4em;margin:0}h1.title{font-size:7em}h2{font-size:2em}",
	"icons": "ico{font-size:2.04em}",
	"iehacks": ".ie .mediumwidth{width:70%;margin-left:0}.ie .mediumwidth hr{margin:100px auto;padding-left:200px}",
	"inputs": "textarea,input{border:1px solid #ccc;outline:0;padding:6px;font-size:.8em;font-family:sans-serif}textarea.smooth,input.smooth{transition:border .15s ease-in-out}textarea:focus,input:focus{border:1px solid #57abb3}textarea,input[type='text']{width:13em}.addon-front{padding:6px 11px 6px 10px;margin-right:-2px;border:1px solid #ccc;border-right:0;font-size:.8em}",
	"messages": "message{display:block;padding:2em 0;background:#ACE}message.warning{background:#D99}message.great{background:#9D9}",
	"navigation": ".navbar{width:100%;background:black;color:white;text-align:left;height:1.5em;padding:1em 0 .6em}.navbar a{text-decoration:none}.pagename{color:white;padding:0 1em 0 2em;font-weight:bold}.navbar-link{padding:.5em;color:#aaa}.navbar-link:hover{color:white}@media(max-width:500px){.navbar a{text-align:center;display:block}.navbar{height:7.5em}}",
	"tables": "table{width:100%;border-spacing:0}.table th,.table td{padding:.5em;line-height:1.4em;text-align:left}tbody tr:nth-child(2n-1){background:#CCC}"
}
